Initial code
UnifiedPush/dart-webpush-encryption pull request #1
Opened 2022-04-06 19:15 UTC by karmanyaahm

To make this ready to publish to pub.dev the git dependency will need to be removed, and for that, webcrypto will need to publish another version.

2022-04-06 20:15 UTC, karmanyaahm commented
@emersion I can't figure out how to request a review from you in the GitHub review section, but can you check this out whenever you're free.

2022-04-14 05:09 UTC, p1gp1g requested changes
It looks great. I just suggest to change some functions name

2022-04-14 05:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +  static Future<WebPushKeys> random() async {
```suggestion
  static Future<WebPushKeys> newKeyPair() async {
```

2022-04-14 05:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +  String get pubKeyWeb => base64UrlEncode(_pubKey);
```suggestion
  String get p256dh => base64UrlEncode(_pubKey);
```

2022-04-14 05:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +  String get authWeb => base64UrlEncode(_authKey);
```suggestion
  String get auth => base64UrlEncode(_authKey);
```

2022-04-14 05:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +  static Future<WebPushKeys> fromBase64(String base64str) {
```suggestion
  static Future<WebPushKeys> deserialize(String base64str) {
```

2022-04-14 05:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +  String get toBase64 =>
```suggestion
  String get serialize =>
```

2022-04-14 05:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +  Map<String, List<int>> get allKeysRaw => {
```suggestion
  Map<String, List<int>> get rawKeys => {
```

2022-06-23 17:25 UTC, merged