SplitWebKeys
UnifiedPush/dart-webpush-encryption pull request #5
Opened 2024-08-17 04:44 UTC by jtmcdole

Breaks out changes from #3 and does an overhaul:
 - Break apart public/private key pairs
 - Split up the library for easier groking.
 - Adds the example from rfc8291 section 5 (sanity check)

(will close out #3 to try and keep things clean)

2024-08-17 08:09 UTC, p1gp1g requested changes
Thank you for the PR !

So I suggest to rename the pubkey and privkey classes `PublicWebPushKey` and `PrivateWebPushKey` to not split `WebPush` and highlight that its a private or public key

I think we should rename `WebPushKeys` to `WebPushKeyPair` or `WebPushKeySet`

And a _keyset_ should always have both _pub_ and _privkey_. When a function needs a _pubkey_, it has to request only the _pubkey_. When it needs a _privkey_, most of the time it also uses the _pubkey_, so the function requests the _keyset_.

2024-08-17 08:09 UTC, p1gp1g commented on lib/src/keys.dart
> +  final WebPrivatePushKey? privateKey;
```suggestion
  final PublicWebPushKey publicKey;
  final PrivateWebPushKey privateKey;
```

I suggest to:
- Rename the variables so "WebPush" is not splitted. Public and Private are set in the beginning to make it clearer.
- Force having both. A key set is a pubkey + privkey

2024-08-17 08:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +    required WebPushKeys clientKeys,
```suggestion
    required PublicWebPushKey clientPubKey,
```

Here we only need the pubKey

2024-08-17 08:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +      final asPubKey = await serverKeys.publicKey!.pubKey;
```suggestion
      final asPubKey = await serverKeys.publicKey.pubKey;
```

As we have the server's key set, there will always be a pubkey and a privkey

2024-08-17 08:09 UTC, p1gp1g commented on lib/webpush_encryption.dart
> +      final asPubKey = await serverKeys.publicKey!.pubKey;
Todo in other occurrences of course

2024-08-17 15:18 UTC, jtmcdole commented
Updated from comments, updated README,  removed some static methods for future testing (mocking) support.

2024-08-19 12:22 UTC, p1gp1g requested changes
There are small changes to do on the readme. Can you explain why it is better to remove static methods ?

After that, it looks good

2024-08-19 12:22 UTC, p1gp1g commented on README.md
> +There are three main classes here, `WebPushKeySet`, `PublicWebPushKey`, `WebPush`.
```suggestion
There are 4 main classes here, `WebPushKeySet`, `PublicWebPushKey`, `PrivateWebPushKey`, `WebPush`.
```

2024-08-19 12:22 UTC, p1gp1g commented on README.md
>  1. Use `.p256dh` and `.auth` to export the keys into the base64 encoding that can be sent to a server.
This should be in (missing) `PublicWebPushKey`, the doc for `PrivateWebPushKey is also missing

2024-08-19 14:37 UTC, jtmcdole commented
>  Can you explain why it is better to remove static methods?

Makes it easier for downstream users to mock WebPush using mockito or mocktail packages. If you want quick access without storing a simple/cheap class allocation, a top-level `const webPush = WebPush()` would work as well - similar to the top level `utf8` class in dart:convert

2024-08-19 16:32 UTC, p1gp1g commented on README.md
```suggestion
1. Use `.newKeyPair()` generate a new key pair (private & public).
1. Use `.publicKey` to get the `PublicWebPushKey` of the key set.
1. Use `.serialize` to serialize the public *AND private keys* for storage. **Be careful with this since it contains the private key.**
   Then, use `WebPushKeys.deserialize` to deserialize that back into an object from the stored string.

In `PublicWebPushKey`:
1. Use `.p256dh` and `.auth` to export the keys into the base64 encoding that can be sent to a server.
```

2024-08-19 16:35 UTC, p1gp1g commented
Thank you for the explanation, I don't know if @karmanyaahm you are available for a review ? I will merge it else :)

2024-08-20 02:31 UTC, karmanyaahm commented
I took a brief look at it and it looks good to me

2024-08-20 07:50 UTC, p1gp1g approved these changes

2024-08-20 07:52 UTC, p1gp1g commented
So I'm merging it. Thank you for the contribution !

I'll publish it to pubdev during the week, feel free to ping me if I forget

2024-08-20 07:52 UTC, merged

2024-08-20 14:33 UTC, jtmcdole commented
Excellent! Can't wait to see it up on pub.dev.  I guess tests are next up.